---
sudo:     false
language: ruby
cache:    bundler
before_install: gem install bundler --no-document
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - '2.3.0'
  - ruby-head
  - jruby-9.2.7.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
